---
- name: Install Apache and Copy HTML File
  hosts: all
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Copy HTML file
      copy:
        src: /home/weblogic/index.html
        dest: /home/bindu.pb17/index.html
